import { expect, test } from '@playwright/test';

test('real dataset replays, pauses, reconnects, completes, and resets identically', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await request.post('/v1/replay/control', { data: { action: 'reset' } });
  await page.goto('/');
  await expect(page.getByText('Connected', { exact: true })).toBeVisible();
  await expect(page.getByText('Start replay to watch transactions arrive.')).toBeVisible();
  await page.getByLabel('Replay speed').selectOption('20');
  await page.getByRole('button', { name: 'Start replay', exact: true }).click();
  await expect.poll(async () => (await (await request.get('/v1/events')).json()).cursor).toBeGreaterThan(20);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(page.locator('.play-state')).toHaveText('paused');
  const paused = await (await request.get('/v1/events')).json();
  await page.locator('.event').first().click();
  await expect(page.locator('.detail-panel')).toContainText(paused.events.at(-1).id);
  await expect(page.locator('.graph canvas').first()).toBeVisible();
  await page.getByLabel('All observed events').check();
  await expect(page.locator('.graph')).toHaveAttribute('aria-label', `Transaction graph showing ${paused.cursor} transfers`);
  await page.screenshot({ path: 'test-results/replay-desktop.png', fullPage: true });
  await page.reload();
  await expect(page.locator('.progress-label')).toHaveText(`${paused.cursor} / ${paused.total} events`);
  expect((await (await request.get('/v1/events')).json()).cursor).toBe(paused.cursor);
  await page.getByRole('button', { name: 'Start replay', exact: true }).click();
  await expect(page.locator('.play-state')).toHaveText('completed', { timeout: 25000 });
  const completed = await (await request.get('/v1/events')).json();
  expect(completed.events).toHaveLength(completed.total);
  expect(completed.events[0]).not.toHaveProperty('label');
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await expect(page.locator('.progress-label')).toHaveText(`0 / ${completed.total} events`);
  await expect(page.getByLabel('Replay speed')).toHaveValue('1');
  await expect(page.locator('.graph')).toHaveAttribute('aria-label', 'Transaction graph showing 0 transfers');
  await page.getByLabel('Replay speed').selectOption('20');
  await page.getByRole('button', { name: 'Start replay', exact: true }).click();
  await expect(page.locator('.play-state')).toHaveText('completed', { timeout: 25000 });
  expect((await (await request.get('/v1/events')).json()).events).toEqual(completed.events);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/replay-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  await request.post('/v1/replay/control', { data: { action: 'reset' } });
});
