import { expect, test } from '@playwright/test';

test('real dataset replays, pauses, reconnects, completes, and resets identically', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await request.post('/v1/replay/control', { data: { action: 'reset' } });
  await page.goto('/');
  await expect(page.getByText('Connected', { exact: true })).toBeVisible();
  await expect(page.getByText('Start replay to watch transactions arrive.')).toBeVisible();
  await page.getByLabel('Replay speed').selectOption('20');
  await page.getByRole('button', { name: 'Start replay', exact: true }).click();
  await expect.poll(async () => (await (await request.get('/v1/events')).json()).cursor).toBeGreaterThan(20);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(page.locator('.play-state')).toHaveText('paused');
  const paused = await (await request.get('/v1/events')).json();
  await page.locator('.event').first().click();
  await expect(page.locator('.detail-panel')).toContainText(paused.events.at(-1).id);
  await expect(page.locator('.workspace .graph canvas').first()).toBeVisible();
  await page.getByLabel('All observed events').check();
  await expect(page.locator('.workspace .graph')).toHaveAttribute('aria-label', `Transaction graph showing ${paused.cursor} transfers`);
  await page.screenshot({ path: 'test-results/replay-desktop.png', fullPage: true });
  await page.reload();
  await expect(page.locator('.progress-label')).toHaveText(`${paused.cursor} / ${paused.total} events`);
  expect((await (await request.get('/v1/events')).json()).cursor).toBe(paused.cursor);
  await page.getByRole('button', { name: 'Start replay', exact: true }).click();
  await expect(page.locator('.play-state')).toHaveText('completed', { timeout: 25000 });
  const completed = await (await request.get('/v1/events')).json();
  expect(completed.events).toHaveLength(completed.total);
  expect(completed.intelligence.status).toBe('ready');
  expect(completed.intelligence.decisions).toHaveLength(completed.total);
  expect(completed.intelligence.cases.length).toBeGreaterThan(0);
  expect(completed.intelligence.cases.every((item: { severity: string }) => item.severity === 'LOW')).toBe(true);
  await page.locator('.case-item').first().click();
  await expect(page.locator('.evidence-card').first()).toBeVisible();
  await expect(page.locator('.case-detail .graph canvas').first()).toBeVisible();
  await expect(page.getByLabel('Inspect case account')).toBeVisible();
  const selectedAccount = await page.getByLabel('Inspect case account').locator('option').last().getAttribute('value');
  await page.getByLabel('Inspect case account').selectOption(selectedAccount!);
  await expect(page.locator('.account-details')).toContainText(selectedAccount!);
  const risk = await (await request.get(`/v1/entities/${encodeURIComponent(selectedAccount!)}/risk`)).json();
  expect(risk.riskScore).toBeNull();
  await page.locator('.evidence-card details').first().locator('summary').click();
  const evidenceTransaction = page.locator('.transaction-links button').first();
  const evidenceTransactionId = await evidenceTransaction.textContent();
  await evidenceTransaction.click();
  await expect(page.locator('.detail-panel')).toContainText(evidenceTransactionId!);
  await page.screenshot({ path: 'test-results/investigation-desktop.png', fullPage: true });
  expect(completed.events[0]).not.toHaveProperty('label');
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await expect(page.locator('.progress-label')).toHaveText(`0 / ${completed.total} events`);
  await expect(page.getByLabel('Replay speed')).toHaveValue('1');
  await expect(page.locator('.workspace .graph')).toHaveAttribute('aria-label', 'Transaction graph showing 0 transfers');
  await expect(page.locator('.case-item')).toHaveCount(0);
  await page.getByLabel('Replay speed').selectOption('20');
  await page.getByRole('button', { name: 'Start replay', exact: true }).click();
  await expect(page.locator('.play-state')).toHaveText('completed', { timeout: 25000 });
  const repeated = await (await request.get('/v1/events')).json();
  expect(repeated.events).toEqual(completed.events);
  expect(repeated.intelligence).toEqual(completed.intelligence);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/replay-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  await request.post('/v1/replay/control', { data: { action: 'reset' } });
});
